# Generated by Django 3.1.6 on 2021-02-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20210224_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='info',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='date',
            new_name='datestamp',
        ),
    ]
