# Generated by Django 3.1.6 on 2021-02-27 15:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20210227_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
